import { h } from 'vue'

export const aliases = {
  cancel: 'cancel',
  checkboxIndeterminate: 'indeterminate_check_box',
  checkboxOff: 'check_box_outline_blank',
  checkboxOn: 'check_box',
  clear: 'cancel',
  close: 'close',
  collapse: 'keyboard_arrow_up',
  complete: 'check',
  delete: 'close_small',
  delimiter: 'circle',
  dropdown: 'arrow_drop_down',
  edit: 'edit',
  error: 'cancel',
  expand: 'keyboard_arrow_down',
  file: 'attach_file',
  first: 'first_page',
  info: 'info',
  last: 'last_page',
  loading: 'cached',
  menu: 'menu',
  minus: 'remove',
  next: 'chevron_right',
  plus: 'add',
  prev: 'chevron_left',
  radioOff: 'radio_button_unchecked',
  radioOn: 'radio_button_checked',
  ratingEmpty: 'star_rate',
  ratingFull: 'star_rate',
  ratingHalf: 'star_rate_half',
  sort: 'sort',
  sortAsc: 'arrow_upward_alt',
  sortDesc: 'arrow_downward_alt',
  subgroup: 'arrow_drop_down',
  success: 'check_circle',
  unfold: 'unfold_more',
  warning: 'warning',
}

export const custom = {
  component: (props) => h(props.tag, { ...props, class: 'material-symbols-outlined' }, props.icon),
}
